import type { WordSet } from './types';

// Default word lists shipped with a fresh install (from the prototype seed).
export const SEED_SETS: WordSet[] = [
  {
    id: 'set-food',
    name: 'Everyday Food & Drink (CEFR A1–A2)',
    carouselSpeed: 4,
    theme: '',
    gradeLevel: '',
    tags: [],
    ttsVoice: 'us',
    positions: {},
    cardScale: {},
    printBlanks: {},
    printMode: 'manual',
    printRandomPercent: 30,
    words: [
      { id: 'w1', text: 'bread', gloss: 'el pan', tier: 'key', clue: 'You use two slices of this to make a sandwich.' },
      { id: 'w2', text: 'water', gloss: 'el agua', tier: 'key', clue: 'A clear drink with no color that you have when you are thirsty.' },
      { id: 'w3', text: 'apple', gloss: 'la manzana', tier: 'key', clue: 'A round red or green fruit that grows on a tree.' },
      { id: 'w4', text: 'rice', gloss: 'el arroz', tier: 'key', clue: 'Small white grains you boil and eat, popular across Asia.' },
      { id: 'w5', text: 'chicken', gloss: 'el pollo', tier: 'key', clue: 'A farm bird, or the meat that comes from it.' },
      { id: 'w6', text: 'breakfast', gloss: 'el desayuno', tier: 'key', clue: 'The first meal of the day, eaten in the morning.' },
      { id: 'w7', text: 'cheese', gloss: 'el queso', tier: 'normal', clue: 'A yellow food made from milk that goes on pizza.' },
      { id: 'w8', text: 'egg', gloss: 'el huevo', tier: 'normal', clue: 'A hen lays this; you can fry or boil it.' },
      { id: 'w9', text: 'fish', gloss: 'el pescado', tier: 'normal', clue: 'An animal that swims in water; people also eat it.' },
      { id: 'w10', text: 'milk', gloss: 'la leche', tier: 'normal', clue: 'A white drink that comes from cows.' },
      { id: 'w11', text: 'soup', gloss: 'la sopa', tier: 'normal', clue: 'A hot liquid food you eat with a spoon.' },
      { id: 'w12', text: 'spoon', gloss: 'la cuchara', tier: 'normal', clue: 'A round tool you use to eat soup or cereal.' },
      { id: 'w13', text: 'plate', gloss: 'el plato', tier: 'normal', clue: 'A flat dish you put your food on.' },
      { id: 'w14', text: 'recipe', gloss: 'la receta', tier: 'bonus', clue: 'The steps that tell you how to cook a dish.' },
      { id: 'w15', text: 'ingredient', gloss: 'el ingrediente', tier: 'bonus', clue: 'One of the foods you need to make a dish.' },
      { id: 'w16', text: 'leftovers', gloss: 'las sobras', tier: 'bonus', clue: 'Food you did not finish, saved to eat later.' },
      { id: 'w17', text: 'appetite', gloss: 'el apetito', tier: 'bonus', clue: 'The feeling of wanting to eat.' },
    ],
  },
  {
    id: 'set-travel',
    name: 'Travel & Transport (CEFR A2)',
    carouselSpeed: 4,
    theme: '',
    gradeLevel: '',
    tags: [],
    ttsVoice: 'us',
    positions: {},
    cardScale: {},
    printBlanks: {},
    printMode: 'manual',
    printRandomPercent: 30,
    words: [
      { id: 't1', text: 'airport', gloss: 'el aeropuerto', tier: 'key', clue: 'The place where planes take off and land.' },
      { id: 't2', text: 'ticket', gloss: 'el billete', tier: 'key', clue: 'A small paper that shows you paid to travel.' },
      { id: 't3', text: 'passport', gloss: 'el pasaporte', tier: 'key', clue: 'A small book you need to travel to other countries.' },
      { id: 't4', text: 'luggage', gloss: 'el equipaje', tier: 'key', clue: 'All the bags you take with you on a trip.' },
      { id: 't5', text: 'train', gloss: 'el tren', tier: 'normal', clue: 'A long vehicle that runs on rails.' },
      { id: 't6', text: 'taxi', gloss: 'el taxi', tier: 'normal', clue: 'A car you pay to drive you somewhere.' },
      { id: 't7', text: 'hotel', gloss: 'el hotel', tier: 'normal', clue: 'A place where you pay to sleep when you travel.' },
      { id: 't8', text: 'map', gloss: 'el mapa', tier: 'normal', clue: 'A drawing that shows you where places are.' },
      { id: 't9', text: 'suitcase', gloss: 'la maleta', tier: 'normal', clue: 'A box with a handle for carrying your clothes on a trip.' },
      { id: 't10', text: 'itinerary', gloss: 'el itinerario', tier: 'bonus', clue: 'A plan that lists where you will go each day.' },
      { id: 't11', text: 'layover', gloss: 'la escala', tier: 'bonus', clue: 'A short wait between two flights.' },
      { id: 't12', text: 'customs', gloss: 'la aduana', tier: 'bonus', clue: 'The place at the border that checks your bags.' },
    ],
  },
];
