import type { WordSet } from './types';

// Default word lists shipped with a fresh install (from the prototype seed).
export const SEED_SETS: WordSet[] = [
  {
    id: 'set-food',
    name: 'Everyday Food & Drink (CEFR A1–A2)',
    carouselSpeed: 4,
    theme: '',
    gradeLevel: '',
    tags: [],
    ttsVoice: 'us',
    positions: {},
    cardScale: {},
    printBlanks: {},
    printMode: 'manual',
    printRandomPercent: 30,
    words: [
      { id: 'w1', text: 'bread', gloss: 'el pan', tier: 'key', clue: 'You use two slices of this to make a sandwich.' },
      { id: 'w2', text: 'water', gloss: 'el agua', tier: 'key', clue: 'A clear drink with no color that you have when you are thirsty.' },
      { id: 'w3', text: 'apple', gloss: 'la manzana', tier: 'key', clue: 'A round red or green fruit that grows on a tree.' },
      { id: 'w4', text: 'rice', gloss: 'el arroz', tier: 'key', clue: 'Small white grains you boil and eat, popular across Asia.' },
      { id: 'w5', text: 'chicken', gloss: 'el pollo', tier: 'key', clue: 'A farm bird, or the meat that comes from it.' },
      { id: 'w6', text: 'breakfast', gloss: 'el desayuno', tier: 'key', clue: 'The first meal of the day, eaten in the morning.' },
      { id: 'w7', text: 'cheese', gloss: 'el queso', tier: 'normal', clue: 'A yellow food made from milk that goes on pizza.' },
      { id: 'w8', text: 'egg', gloss: 'el huevo', tier: 'normal', clue: 'A hen lays this; you can fry or boil it.' },
      { id: 'w9', text: 'fish', gloss: 'el pescado', tier: 'normal', clue: 'An animal that swims in water; people also eat it.' },
      { id: 'w10', text: 'milk', gloss: 'la leche', tier: 'normal', clue: 'A white drink that comes from cows.' },
      { id: 'w11', text: 'soup', gloss: 'la sopa', tier: 'normal', clue: 'A hot liquid food you eat with a spoon.' },
      { id: 'w12', text: 'spoon', gloss: 'la cuchara', tier: 'normal', clue: 'A round tool you use to eat soup or cereal.' },
      { id: 'w13', text: 'plate', gloss: 'el plato', tier: 'normal', clue: 'A flat dish you put your food on.' },
      { id: 'w14', text: 'recipe', gloss: 'la receta', tier: 'bonus', clue: 'The steps that tell you how to cook a dish.' },
      { id: 'w15', text: 'ingredient', gloss: 'el ingrediente', tier: 'bonus', clue: 'One of the foods you need to make a dish.' },
      { id: 'w16', text: 'leftovers', gloss: 'las sobras', tier: 'bonus', clue: 'Food you did not finish, saved to eat later.' },
      { id: 'w17', text: 'appetite', gloss: 'el apetito', tier: 'bonus', clue: 'The feeling of wanting to eat.' },
    ],
  },
  {
    id: 'set-travel',
    name: 'Travel & Transport (CEFR A2)',
    carouselSpeed: 4,
    theme: '',
    gradeLevel: '',
    tags: [],
    ttsVoice: 'us',
    positions: {},
    cardScale: {},
    printBlanks: {},
    printMode: 'manual',
    printRandomPercent: 30,
    words: [
      { id: 't1', text: 'airport', gloss: 'el aeropuerto', tier: 'key', clue: 'The place where planes take off and land.' },
      { id: 't2', text: 'ticket', gloss: 'el billete', tier: 'key', clue: 'A small paper that shows you paid to travel.' },
      { id: 't3', text: 'passport', gloss: 'el pasaporte', tier: 'key', clue: 'A small book you need to travel to other countries.' },
      { id: 't4', text: 'luggage', gloss: 'el equipaje', tier: 'key', clue: 'All the bags you take with you on a trip.' },
      { id: 't5', text: 'train', gloss: 'el tren', tier: 'normal', clue: 'A long vehicle that runs on rails.' },
      { id: 't6', text: 'taxi', gloss: 'el taxi', tier: 'normal', clue: 'A car you pay to drive you somewhere.' },
      { id: 't7', text: 'hotel', gloss: 'el hotel', tier: 'normal', clue: 'A place where you pay to sleep when you travel.' },
      { id: 't8', text: 'map', gloss: 'el mapa', tier: 'normal', clue: 'A drawing that shows you where places are.' },
      { id: 't9', text: 'suitcase', gloss: 'la maleta', tier: 'normal', clue: 'A box with a handle for carrying your clothes on a trip.' },
      { id: 't10', text: 'itinerary', gloss: 'el itinerario', tier: 'bonus', clue: 'A plan that lists where you will go each day.' },
      { id: 't11', text: 'layover', gloss: 'la escala', tier: 'bonus', clue: 'A short wait between two flights.' },
      { id: 't12', text: 'customs', gloss: 'la aduana', tier: 'bonus', clue: 'The place at the border that checks your bags.' },
    ],
  },
  {
    id: 'set-animals',
    name: 'Animals (CEFR A1–A2)',
    carouselSpeed: 4,
    theme: '',
    gradeLevel: '',
    tags: [],
    ttsVoice: 'us',
    positions: {},
    cardScale: {},
    printBlanks: {},
    printMode: 'manual',
    printRandomPercent: 30,
    words: [
      { id: 'a1', text: 'dog', gloss: 'el perro', tier: 'key', clue: 'A friendly pet that barks and wags its tail.' },
      { id: 'a2', text: 'cat', gloss: 'el gato', tier: 'key', clue: 'A soft pet that says meow and likes to nap.' },
      { id: 'a3', text: 'bird', gloss: 'el pájaro', tier: 'key', clue: 'A small animal with feathers and wings that can fly.' },
      { id: 'a4', text: 'horse', gloss: 'el caballo', tier: 'key', clue: 'A big animal you can ride, with a long tail and mane.' },
      { id: 'a5', text: 'cow', gloss: 'la vaca', tier: 'normal', clue: 'A large farm animal that gives us milk.' },
      { id: 'a6', text: 'rabbit', gloss: 'el conejo', tier: 'normal', clue: 'A small animal with long ears that hops.' },
      { id: 'a7', text: 'lion', gloss: 'el león', tier: 'normal', clue: 'A big wild cat with a loud roar, king of the jungle.' },
      { id: 'a8', text: 'elephant', gloss: 'el elefante', tier: 'normal', clue: 'A huge gray animal with big ears and a long trunk.' },
      { id: 'a9', text: 'monkey', gloss: 'el mono', tier: 'normal', clue: 'An animal that climbs trees and loves bananas.' },
      { id: 'a10', text: 'bear', gloss: 'el oso', tier: 'normal', clue: 'A big furry animal that sleeps all winter.' },
      { id: 'a11', text: 'duck', gloss: 'el pato', tier: 'normal', clue: 'A bird that swims on ponds and says quack.' },
      { id: 'a12', text: 'frog', gloss: 'la rana', tier: 'normal', clue: 'A small green animal that jumps and lives near water.' },
      { id: 'a13', text: 'penguin', gloss: 'el pingüino', tier: 'bonus', clue: 'A black-and-white bird that cannot fly but loves cold places.' },
      { id: 'a14', text: 'dolphin', gloss: 'el delfín', tier: 'bonus', clue: 'A smart, friendly sea animal that leaps out of the waves.' },
      { id: 'a15', text: 'giraffe', gloss: 'la jirafa', tier: 'bonus', clue: 'The tallest animal, with a very long neck and brown spots.' },
    ],
  },
  {
    id: 'set-weather',
    name: 'Weather (CEFR A1–A2)',
    carouselSpeed: 4,
    theme: '',
    gradeLevel: '',
    tags: [],
    ttsVoice: 'us',
    positions: {},
    cardScale: {},
    printBlanks: {},
    printMode: 'manual',
    printRandomPercent: 30,
    words: [
      { id: 'we1', text: 'sun', gloss: 'el sol', tier: 'key', clue: 'The bright light in the sky that keeps us warm during the day.' },
      { id: 'we2', text: 'rain', gloss: 'la lluvia', tier: 'key', clue: 'Drops of water that fall from the sky; take a coat.' },
      { id: 'we3', text: 'wind', gloss: 'el viento', tier: 'key', clue: 'Moving air that can blow your hat away.' },
      { id: 'we4', text: 'snow', gloss: 'la nieve', tier: 'key', clue: 'Soft white flakes that fall when it is very cold.' },
      { id: 'we5', text: 'cloud', gloss: 'la nube', tier: 'normal', clue: 'A white or gray shape in the sky that can bring a shower.' },
      { id: 'we6', text: 'storm', gloss: 'la tormenta', tier: 'normal', clue: 'Very bad weather with strong gusts and heavy showers.' },
      { id: 'we7', text: 'hot', gloss: 'caluroso', tier: 'normal', clue: 'How it feels in summer when the sun is strong.' },
      { id: 'we8', text: 'cold', gloss: 'frío', tier: 'normal', clue: 'How it feels in winter; you need a warm coat.' },
      { id: 'we9', text: 'fog', gloss: 'la niebla', tier: 'normal', clue: 'A thick mist near the ground that makes it hard to see.' },
      { id: 'we10', text: 'rainbow', gloss: 'el arcoíris', tier: 'normal', clue: 'A curve of many colors in the sky after a shower.' },
      { id: 'we11', text: 'thunder', gloss: 'el trueno', tier: 'bonus', clue: 'The loud booming sound in the sky during bad weather.' },
      { id: 'we12', text: 'lightning', gloss: 'el relámpago', tier: 'bonus', clue: 'A sudden bright flash you see in the sky during bad weather.' },
      { id: 'we13', text: 'umbrella', gloss: 'el paraguas', tier: 'bonus', clue: 'You open this to stay dry during a shower.' },
      { id: 'we14', text: 'forecast', gloss: 'el pronóstico', tier: 'bonus', clue: 'What the weather person on TV says tomorrow will be like.' },
    ],
  },
  {
    id: 'set-family',
    name: 'Family (CEFR A1–A2)',
    carouselSpeed: 4,
    theme: '',
    gradeLevel: '',
    tags: [],
    ttsVoice: 'us',
    positions: {},
    cardScale: {},
    printBlanks: {},
    printMode: 'manual',
    printRandomPercent: 30,
    words: [
      { id: 'fa1', text: 'mom', gloss: 'la mamá', tier: 'key', clue: 'The female parent in your family.' },
      { id: 'fa2', text: 'dad', gloss: 'el papá', tier: 'key', clue: 'The male parent in your family.' },
      { id: 'fa3', text: 'family', gloss: 'la familia', tier: 'key', clue: 'All the people who are related to you.' },
      { id: 'fa4', text: 'sister', gloss: 'la hermana', tier: 'key', clue: 'A girl who has the same parents as you.' },
      { id: 'fa5', text: 'brother', gloss: 'el hermano', tier: 'normal', clue: 'A boy who has the same parents as you.' },
      { id: 'fa6', text: 'baby', gloss: 'el bebé', tier: 'normal', clue: 'A very young child who cannot walk or talk yet.' },
      { id: 'fa7', text: 'grandma', gloss: 'la abuela', tier: 'normal', clue: 'The mother of one of your parents.' },
      { id: 'fa8', text: 'grandpa', gloss: 'el abuelo', tier: 'normal', clue: 'The father of one of your parents.' },
      { id: 'fa9', text: 'aunt', gloss: 'la tía', tier: 'normal', clue: "Your parent's sister." },
      { id: 'fa10', text: 'uncle', gloss: 'el tío', tier: 'normal', clue: "Your parent's brother." },
      { id: 'fa11', text: 'cousin', gloss: 'el primo', tier: 'normal', clue: 'The child of your aunt or uncle.' },
      { id: 'fa12', text: 'parents', gloss: 'los padres', tier: 'bonus', clue: 'Your mother and father together.' },
      { id: 'fa13', text: 'twins', gloss: 'los gemelos', tier: 'bonus', clue: 'Two children born on the same day to the same mother.' },
      { id: 'fa14', text: 'relative', gloss: 'el pariente', tier: 'bonus', clue: 'Any person who belongs to your family.' },
    ],
  },
  {
    id: 'set-classroom',
    name: 'Classroom Objects (CEFR A1–A2)',
    carouselSpeed: 4,
    theme: '',
    gradeLevel: '',
    tags: [],
    ttsVoice: 'us',
    positions: {},
    cardScale: {},
    printBlanks: {},
    printMode: 'manual',
    printRandomPercent: 30,
    words: [
      { id: 'cl1', text: 'pen', gloss: 'el bolígrafo', tier: 'key', clue: 'You hold this to write with ink.' },
      { id: 'cl2', text: 'book', gloss: 'el libro', tier: 'key', clue: 'You read pages of words in this.' },
      { id: 'cl3', text: 'desk', gloss: 'el pupitre', tier: 'key', clue: 'The small table where a student sits and works.' },
      { id: 'cl4', text: 'chair', gloss: 'la silla', tier: 'key', clue: 'You sit on this at your desk.' },
      { id: 'cl5', text: 'pencil', gloss: 'el lápiz', tier: 'normal', clue: 'You write with this, and an eraser can rub it out.' },
      { id: 'cl6', text: 'eraser', gloss: 'la goma', tier: 'normal', clue: 'You use this to rub out a pencil mistake.' },
      { id: 'cl7', text: 'ruler', gloss: 'la regla', tier: 'normal', clue: 'A flat tool with numbers for drawing straight lines.' },
      { id: 'cl8', text: 'backpack', gloss: 'la mochila', tier: 'normal', clue: 'You carry your books and pens to school in this.' },
      { id: 'cl9', text: 'scissors', gloss: 'las tijeras', tier: 'normal', clue: 'You use these to cut paper.' },
      { id: 'cl10', text: 'board', gloss: 'la pizarra', tier: 'normal', clue: 'The big flat surface at the front where the teacher writes.' },
      { id: 'cl11', text: 'glue', gloss: 'el pegamento', tier: 'normal', clue: 'A sticky liquid you use to join paper together.' },
      { id: 'cl12', text: 'crayon', gloss: 'el crayón', tier: 'bonus', clue: 'A stick of colored wax for drawing pictures.' },
      { id: 'cl13', text: 'notebook', gloss: 'el cuaderno', tier: 'bonus', clue: 'A pad of empty pages where you write your notes.' },
      { id: 'cl14', text: 'marker', gloss: 'el marcador', tier: 'bonus', clue: 'A colored pen with a thick tip for writing on the board.' },
    ],
  },
];
