import type { WordSet } from './types';

// Default word lists shipped with a fresh install (from the prototype seed).
export const SEED_SETS: WordSet[] = [
  {
    id: 'set-food',
    name: 'Everyday Food & Drink (CEFR A1–A2)',
    carouselSpeed: 4,
    theme: '',
    gradeLevel: '',
    tags: [],
    ttsVoice: 'us',
    positions: {},
    cardScale: {},
    printBlanks: {},
    printMode: 'manual',
    printRandomPercent: 30,
    words: [
      { id: 'w1', text: 'bread', gloss: 'el pan', tier: 'key' },
      { id: 'w2', text: 'water', gloss: 'el agua', tier: 'key' },
      { id: 'w3', text: 'apple', gloss: 'la manzana', tier: 'key' },
      { id: 'w4', text: 'rice', gloss: 'el arroz', tier: 'key' },
      { id: 'w5', text: 'chicken', gloss: 'el pollo', tier: 'key' },
      { id: 'w6', text: 'breakfast', gloss: 'el desayuno', tier: 'key' },
      { id: 'w7', text: 'cheese', gloss: 'el queso', tier: 'normal' },
      { id: 'w8', text: 'egg', gloss: 'el huevo', tier: 'normal' },
      { id: 'w9', text: 'fish', gloss: 'el pescado', tier: 'normal' },
      { id: 'w10', text: 'milk', gloss: 'la leche', tier: 'normal' },
      { id: 'w11', text: 'soup', gloss: 'la sopa', tier: 'normal' },
      { id: 'w12', text: 'spoon', gloss: 'la cuchara', tier: 'normal' },
      { id: 'w13', text: 'plate', gloss: 'el plato', tier: 'normal' },
      { id: 'w14', text: 'recipe', gloss: 'la receta', tier: 'bonus' },
      { id: 'w15', text: 'ingredient', gloss: 'el ingrediente', tier: 'bonus' },
      { id: 'w16', text: 'leftovers', gloss: 'las sobras', tier: 'bonus' },
      { id: 'w17', text: 'appetite', gloss: 'el apetito', tier: 'bonus' },
    ],
  },
  {
    id: 'set-travel',
    name: 'Travel & Transport (CEFR A2)',
    carouselSpeed: 4,
    theme: '',
    gradeLevel: '',
    tags: [],
    ttsVoice: 'us',
    positions: {},
    cardScale: {},
    printBlanks: {},
    printMode: 'manual',
    printRandomPercent: 30,
    words: [
      { id: 't1', text: 'airport', gloss: 'el aeropuerto', tier: 'key' },
      { id: 't2', text: 'ticket', gloss: 'el billete', tier: 'key' },
      { id: 't3', text: 'passport', gloss: 'el pasaporte', tier: 'key' },
      { id: 't4', text: 'luggage', gloss: 'el equipaje', tier: 'key' },
      { id: 't5', text: 'train', gloss: 'el tren', tier: 'normal' },
      { id: 't6', text: 'taxi', gloss: 'el taxi', tier: 'normal' },
      { id: 't7', text: 'hotel', gloss: 'el hotel', tier: 'normal' },
      { id: 't8', text: 'map', gloss: 'el mapa', tier: 'normal' },
      { id: 't9', text: 'suitcase', gloss: 'la maleta', tier: 'normal' },
      { id: 't10', text: 'itinerary', gloss: 'el itinerario', tier: 'bonus' },
      { id: 't11', text: 'layover', gloss: 'la escala', tier: 'bonus' },
      { id: 't12', text: 'customs', gloss: 'la aduana', tier: 'bonus' },
    ],
  },
];
